### ISSUE TITLE
Talks about further updates

### ISSUE THREAD

**Issue by pioneerit** [vkhatri/chef-aerospike-cluster#19]
Hi @vkhatri, thanks for adding me.
I've just got this morning access to the Enterprise version.
And I'll have access to TB's Aerospike Cluster to test the cookbook in real life :)

Mostly I'm concentrated on the latest versions, so the first question:
1. Can I update default attributes and settings to the latest one?

Regarding checksum checking. If I'll update to the latest version or anyone try to do it manually they will get an error because of this. It's mean, that I should check checksum manually. And I'm not doing things manually. As Aerospike can't provide any good solutions for verifying the packages, I'd leave that feature with the better description in Readme, but disabled by default.
2. Do you really need checksum by default?

And the last one,
3. I'd like to continue making PR for new changes for the review, if you don't mind. Do you?

**Comment by vkhatri** [comment]
@pioneerit 

#-1. Yes, cookbook should always point to the latest version, i will also test it in my environment over the weekend.

#-2. Yes, checksum is always better to apply to a `remote_file` resource. It is also a security measure.

#-3. Sound great!

**Comment by pioneerit** [comment]
So far so good. I think it is closed
