### ISSUE TITLE
Aerospike versions and file names.

### ISSUE THREAD

**Issue by paul-grozav** [vkhatri/chef-aerospike-cluster#24]
Aerospike server enterprise 3.10.1.1 has these two packages:

aerospike-server-enterprise-3.10.1.1.ubuntu14.04.x86_64.deb
aerospike-tools-3.10.2.ubuntu14.04.x86_64.deb

I mean:
server-version=3.10.1.1
tools-version=3.10.2

This does not seem to match algorithm from : https://github.com/vkhatri/chef-aerospike-cluster/blob/master/recipes/package.rb#L86

**Comment by paul-grozav** [comment]
3.9.1.1 seems to be the latest version that works with that algorithm:
it contains
server-version=3.9.1.1
tools-version=3.9.1.2
that is node['aerospike']['version'].split('.')[0..2].join('.') + node['aerospike']['package_suffix'] which could be 2.

Actually, no, that would not work, because the suffix is also used for the server-version as well. I thinks the simple solution would be to specify two versions, one for the server and one for the tools, or get them from the file system/file names.

**Comment by paul-grozav** [comment]
For now, I switched to 3.9.0.3, which seems to be the latest version that is supported by this recipe. Thanks

**Comment by vkhatri** [comment]
@paul-grozav Thank you for reporting the issue, looks like server and tools package install needs to be handled separately.

Will update the cookbook sooner.

**Comment by vkhatri** [comment]
@paul-grozav fixed, release new cookbook version v0.2.0?

**Comment by paul-grozav** [comment]
`remote_file 'download_tools_package_file'`  ?

`==> default: [2016-12-23T19:21:36+00:00] WARN: remote_file[download_tools_package_file] cannot be downloaded from http://www.aerospike.com/enterprise/download/tools/3.10.2/artifact/ubuntu14: 404 "Not Found"`

Thanks for your prompt response, and trying to keep the project up to date with the new versions of AeroSpike.

While testing v0.2.0, I saw that you tried to download the tools package ... that package is inside the server archive. When you download the server, you get a .tgz, that has two .deb files inside, one is the server package and the other is the tools package. The previous version was handling this part just fine. The only problem was when creating the tools package file name.

Thank you, again!

**Comment by vkhatri** [comment]
I was afraid that there might be some untested changes for `enterprise` version.

`Tools` package is available [here](http://www.aerospike.com/download/tools/3.10.2/) to download. It is the similar package bundled inside server package for `community` edition.

I noticed that `tools` package is not `edition` categorized, perhaps it is common for both `enterprise` and `community`.

Could you please verify that the `tools` package available [here](http://www.aerospike.com/download/tools/3.10.2/) and the one bundled in `enterprise server` package are the same?

**Comment by paul-grozav** [comment]
Yes, they seem to be the same(the tools package from your link, is the same with the tools from enterprise .tgz).

So do you plan to always download the tools, from that URL, no matter if the server is community or enterprise?

I was thinking about the other way of doing it. Simply downloading the enterprise .tgz and run ./asinstall that will install the server and tools pakages, as described in their [documentation](http://www.aerospike.com/docs/operations/install/linux/ubuntu).

Although, the packages seem to be the same, maybe in future releases there will be two different packages, for community/enterprise ...

I don't know, it's your choice after all. I'm happy with either solution 😃 . Thanks!

**Comment by vkhatri** [comment]
I would like to keep the dependency on just one `.tar` package for both. But it looks like `tools` package is developed separately [here](http://www.aerospike.com/download/tools/notes.html#3.10.2).

I believe it is packaged with `server` because of `asinstall` which makes install a bit easier.

I prefer to keep it separate, as there might be scenarios where you just want to upgrade `tools` - which never might happen but it is a good practice.

Thank you for confirming that `servers` and `tools` packages are the same. Cookbook `v0.2.0` already download `tools` from its own URL.

Yes, I will make it generic for `edition`. So that both `enterprise` and `community` gets the same `tools` package. Will publish `v0.2.1` with the changes.

**Comment by vkhatri** [comment]
@paul-grozav Updated and Released cookbook version v0.2.1.

**Comment by paul-grozav** [comment]
Everything seems fine on my side. Version v0.2.1 seems to support AeroSpike enterprise 3.10.0.3 with AMC and all. Thanks for everything!

P.S.: I'm O.K. with closing this issue.

**Comment by vkhatri** [comment]
@paul-grozav Thank you for the confirmation.

👍
