### ISSUE TITLE
enterprise edition package url returns 401 during http redirects

### ISSUE THREAD

**Issue by vkhatri** [vkhatri/chef-aerospike-cluster#8]
While downloading enterprise package `.tzg` file, there is a `401` response during url redirects which causes failure to `remote_file` resource.

Temporary fix is to download the file separately for `enterprise` edition.

**Comment by vkhatri** [comment]
using `curl` as a temporary fix for now.

**Comment by vkhatri** [comment]
@pioneerit  What is your Chef Supermarket user id?

**Comment by pioneerit** [comment]
@vkhatri: [pioneer](https://supermarket.chef.io/users/pioneer)

**Comment by vkhatri** [comment]
@pioneerit Thanks! I have added you as a Collaborator in [Supermarket](https://supermarket.chef.io/cookbooks/aerospike-cluster).
